# Python type stub file for pybbhash
from typing import Iterable, Dict, List, Optional, Union
from pathlib import Path

__version__: str
__author__: str
__license__: str

class bitvector:
    def __init__(self, size: int) -> None: ...
    def get(self, i: int) -> bool: ...
    def set(self, i: int) -> None: ...
    def clear(self) -> None: ...
    def rank(self, i: int) -> int: ...
    def build_ranks(self, offset: int = 0) -> int: ...

class SingleHashFunctor:
    def __init__(self) -> None: ...
    def __call__(self, key: int) -> int: ...

class XorshiftHashFunctors:
    def __init__(self, base: SingleHashFunctor) -> None: ...
    def h0(self, state: List[int], key: int) -> int: ...
    def h1(self, state: List[int], key: int) -> int: ...
    def next(self, state: List[int]) -> int: ...

class mphf:
    _gamma: float
    _nelem: int
    _nb_levels: int
    _lastbitsetrank: int
    _final_hash: Dict[int, int]
    _built: bool

    def __init__(
        self,
        n: int = 0,
        input_range: Optional[Iterable[int]] = None,
        num_thread: int = 1,
        gamma: float = 2.0,
        writeEach: bool = False,
        progress: bool = False,
        perc_elem_loaded: float = 0.03,
    ) -> None: ...
    def lookup(self, elem: int) -> int: ...
    def nbKeys(self) -> int: ...
    def save(self, path: Union[str, Path]) -> None: ...
    @staticmethod
    def load(fpath: Union[str, Path]) -> mphf: ...

__all__: List[str]
