#!/usr/bin/env python3
"""Verify C++-generated MPHF binary can be loaded in Python."""

import sys
import os
import csv

# Add parent directory to import pybbhash
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from pybbhash.boophf import mphf


def main():
    print("\n=== Python verification of C++ export ===\n")
    
    # Load expected results from CSV generated by C++
    expected = {}
    csv_file = "test_data_cpp.csv"
    
    if not os.path.exists(csv_file):
        print(f"✗ CSV file not found: {csv_file}")
        print("  Please run the C++ test first to generate the file.")
        return False
    
    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            key = int(row['key'])
            hash_value = int(row['hash_value'])
            expected[key] = hash_value
    
    print(f"✓ Loaded {len(expected)} expected key-value pairs from CSV")
    
    # Load MPHF from C++ binary
    binary_file = "test_data_cpp.mphf"
    if not os.path.exists(binary_file):
        print(f"✗ Binary file not found: {binary_file}")
        print("  Please run the C++ test first to generate the file.")
        return False
    
    mph = mphf.load(binary_file)
    print(f"✓ Loaded MPHF from C++ binary")
    
    # Print MPHF info
    print(f"\nMPHF Statistics:")
    print(f"  Number of keys: {mph._nelem}")
    print(f"  Gamma: {mph._gamma}")
    print(f"  Number of levels: {mph._nb_levels}")
    print(f"  Last bitset rank: {mph._lastbitsetrank}")
    print(f"  Final hash size: {len(mph._final_hash)}")
    
    # Verify all lookups
    mismatches = 0
    matches = 0
    
    for key, expected_val in expected.items():
        actual_val = mph.lookup(key)
        
        if actual_val != expected_val:
            print(f"✗ Mismatch for key {key}: expected {expected_val}, got {actual_val}")
            mismatches += 1
            if mismatches >= 10:
                print("  (stopping after 10 mismatches)")
                break
        else:
            matches += 1
    
    # Print results
    print(f"\n{'='*50}")
    if mismatches == 0:
        print(f"✓ All {matches} lookups match!")
        print(f"✓ C++ → Python binary format compatibility verified!")
        return True
    else:
        print(f"✗ Found {mismatches} mismatches out of {len(expected)} keys")
        return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
